version: '3.9'
services:
  premia-orderbook:
    env_file: .env
    restart: on-failure
    build: .
    ports:
      - '3000:3000'
#  premia-orderbook-ngrok:
#    depends_on: [ premia-orderbook ]
#    image: ngrok/ngrok
#    environment:
#      NGROK_CONFIG: /etc/ngrok/ngrok.yml
#    volumes:
#      - ./ngrok:/etc/ngrok
#    command: http --domain=premia.api-v3.ngrok.dev premia-orderbook:3000