version: '3.9'
services:
  premia-orderbook:
    env_file: .env
    restart: on-failure
    build: .
    ports:
      - '3000:3000'
#  premia-dashboard:
#    env_file: dashboard/.env
#    restart: on-failure
#    build: dashboard
#    ports:
#      - '3010:3010'